name: Deploy Google Cloud Function

on:
  push:
    branches:
      - dev
      - test
      - prod
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Python Dependencies
      run: pip install -r src/requirements.txt
      working-directory: ${{ github.workspace }}

    - name: Package the Cloud Function
      run: |
        zip -r hello-pubsub.zip functions/ main.py
      working-directory: src

    - name: Move Zip to Terraform Directory
      run: mv src/hello-pubsub.zip terraform/hello-pubsub.zip

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: "1.0.x"
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Debug Workspace Name
      run: |
        echo "Workspace name to be used: gcp_enviornments-${{ github.ref_name }}"
      working-directory: terraform

    
    - name: Debug Initialization and Workspace Selection
      run: |
        echo "Initializing Terraform..."
        terraform init
        echo "Initialization complete."
        workspace_name="${{ github.ref_name }}"
        echo "Selecting or creating workspace named $workspace_name"
        terraform workspace select "$workspace_name" || echo "Workspace $workspace_name does not exist, creating it..." && terraform workspace new "$workspace_name"
      working-directory: terraform
      env:
        TF_INPUT: false

    - name: Terraform Plan
      run: terraform plan
      working-directory: terraform

    - name: Terraform Apply
      if: github.ref == 'refs/heads/prod' || github.ref == 'refs/heads/test'
      run: terraform apply -auto-approve
      working-directory: terraform

    - name: List Terraform State
      run: terraform state list
      working-directory: terraform

    - name: Cleanup Artifacts
      run: rm -f terraform/hello-pubsub.zip
