name: Deploy Google Cloud Function

on:
  push:
    branches:
      - dev
      - test
      - prod
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Python Dependencies
      run: pip install -r src/requirements.txt
      working-directory: ${{ github.workspace }}

    - name: Package the Cloud Function
      run: |
        zip -r hello-pubsub.zip functions/ main.py
      working-directory: src

    - name: Move Zip to Terraform Directory
      run: mv src/hello-pubsub.zip terraform/hello-pubsub.zip

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: "1.7.5"
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}   
        
    - name: Verify GCloud Auth
      run: gcloud auth list   

    - name: Debug Workspace Name
      run: |
        echo "Workspace name to be used: ${{ github.ref_name }}"
      working-directory: terraform

    
    - name: Terraform Init
      run: terraform init
        
      working-directory: terraform
      env:
        TF_INPUT: false

    - name: Terraform Plan
      run: terraform plan
      working-directory: terraform

    - name: Terraform Apply
      if: github.ref == 'refs/heads/prod' || github.ref == 'refs/heads/test'
      run: terraform apply -auto-approve
      working-directory: terraform

    - name: List Terraform State
      run: terraform state list
      working-directory: terraform

    - name: Cleanup Artifacts
      run: rm -f terraform/hello-pubsub.zip
